# Generated by Django 3.0.6 on 2021-03-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
